### ISSUE TITLE
SDK blocked by AdBlock on demo page

### ISSUE THREAD

**Issue by noxonsu** [sakurity/securelogin#1]
http://joxi.ru/52a1YDyT8o5O20

**Comment by homakov** [comment]
@noxonsu  just installed ABP, can you please share your lists? By default it does not block

**Comment by noxonsu** [comment]
https://easylist.to/
https://forums.lanik.us/viewforum.php?f=102

**Comment by homakov** [comment]
Ok, just installed all those lists but still cannot reproduce.

Anyway, this is not a real SDK, just 40 LOC helper that must be hosted by clients. It was moved to cobased.com now - does it work?
