### ISSUE TITLE
Add flow diagram

### ISSUE THREAD

**Issue by srigi** [sakurity/securelogin#14]
I'm really missing the flow diagram. Sharing a showing code examples is nice. So are animated gifs. But this repository is missing one key ingredient - how it works. This information should be right at the main page.

Here is example of a such diagram:
![oauth2 flow diagram](https://docs.oracle.com/cd/E39820_01/doc.11121/gateway_docs/content/images/oauth/oauth_web_server_flow.png)

**Comment by homakov** [comment]
@srigi what do you think?
![slflow](https://user-images.githubusercontent.com/174693/26845447-26c08c22-4aff-11e7-9a31-9ce8f74fcd37.png)

**Comment by srigi** [comment]
Awesome
