### ISSUE TITLE
Comparison with SQRL

### ISSUE THREAD

**Issue by frederikcreemers** [sakurity/securelogin#26]
I like the comparison table in the READMe, and would love to see a comparison to Steve Gibson's [SQRL](https://www.grc.com/sqrl/sqrl.htm) protocol in there. I'm an avid listener of his Security now podcast, and his protocol was the first decentralized passwordless protocol I heard about. It got me really excited.

**Comment by homakov** [comment]
@bigblind many people request it. It has same goals and more-less similar architecture, as far as I know. 
From what I know their protocol is not finalized and I could not find a demo. Once they have it, I will add it to the table.
