### ISSUE TITLE
I can't remove the app on Android

### ISSUE THREAD

**Issue by marcelgalema** [sakurity/securelogin#27]
The installer crashes all the time on my Samsung S6. Now what?

**Comment by homakov** [comment]
You can't install or you can't remove it? 

It's not problem on our side, SL is regular cordova app and has nothing but HTML and JS. Cordova is a well tested framework. So it's fault of samsung/android. (I own S8 and oh God it's buggy)

**Comment by marcelgalema** [comment]
Installing was fine, uninstalling crashes.

Marcel

Op 14 jun. 2017 10:11 schreef "Egor Homakov" <notifications@github.com>:

**Comment by marcelgalema** [comment]
Screenshot attachef
![screenshot_20170614-181348](https://user-images.githubusercontent.com/130738/27143127-8afa77e6-512d-11e7-8b3f-430e7946edae.png)

**Comment by homakov** [comment]
rolled out new version - hopefully after update it will be possible to remove?

anyway, cannot really do anything: this is bug of android

**Comment by marcelgalema** [comment]
Yes, fixed!!

**Comment by homakov** [comment]
oh, than it must be Cordova bug. this software is still largely experimental, not tested with most devices
