### ISSUE TITLE
OSX client errors

### ISSUE THREAD

**Issue by dixflatlinr** [sakurity/securelogin#5]
MacOS client gives the message:

"You don't have SecureLogin profiles. "

Then nothing happens :O. What I'm doing wrong? 

I just dl'ed the client, installed it, then tried the demo page, but gives the same message every time. The web based client works.

**Comment by homakov** [comment]
Did you open the client and created a profile?
From now on it will redirect back to main screen instead of failing.

**Comment by MattKetmo** [comment]
I experienced the same the first time I opened the app: a blank home screen and the message "You don't have SecureLogin profiles".
After exiting (2 times I think) it finally displayed the form to create a profile.

**Comment by dixflatlinr** [comment]
The same happened what MattKetmo described, but now it works just fine. Thanks!

**Comment by homakov** [comment]
Figured out: user was supposed to open an app they just downloaded and create a profile there. 

It will be fixed, thanks.

**Comment by datfinesoul** [comment]
I've opened the OS X app, created a profile, then tried using the demo https://cobased.com/ while having the app open, and i always just get the "provider is required" message from the app, even though it shows me logged in.

**Comment by homakov** [comment]
@datfinesoul sorry: the protocol was changed after we potential phishing reports. Now as phishing is fixed on protocol level, I'll ping when new clients roll out soon

**Comment by homakov** [comment]
no more alerts from now on
